MenuScreen
teamten5/source pull request #9
Opened 2022-12-20 15:41 UTC by E-Gruff

2022-12-20 16:16 UTC, chloe-eolhc requested changes

2022-12-20 16:16 UTC, chloe-eolhc commented on core/src/io/github/teamten5/views/MenuScreen.java
> +                Skin skin = new Skin(Gdx.files.internal("skin/glassy-ui.json"));
this file isn't here

2022-12-20 17:04 UTC, chloe-eolhc approved these changes

2022-12-30 00:00 UTC, eddiebarun approved these changes

2023-01-03 11:53 UTC, merged